services:
  - type: web
    name: waqt-min-dahab
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
